[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Nick Piepmeier <pieps@google.com>"]
edition = "2018"

[dependencies]
itertools = "0.10"
lazy_static = "1.4"
rayon = "1.5"
regex = "1.4"
gumdrop = "0.8"
num = "0.1.32"
