[package]
name = "day11"
version = "0.1.0"
authors = ["Nick Piepmeier <pieps@google.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10"
