[package]
name = "day8"
version = "0.1.0"
authors = ["Nick Piepmeier <pieps@google.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4"
lazy_static = "1.4"
rayon = "1.5"
